// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5f8-VW6KnZHmz6ia0_2uEVDPuLU8qpx4',
    appId: '1:445806361703:android:d8ce7239beb9d8d98fe8c2',
    messagingSenderId: '445806361703',
    projectId: 'mindflow-f4a56',
    storageBucket: 'mindflow-f4a56.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGWakZREvLNjFJP1il9zKD_HE7pHEKsE',
    appId: '1:445806361703:ios:586364891f8b3baa8fe8c2',
    messagingSenderId: '445806361703',
    projectId: 'mindflow-f4a56',
    storageBucket: 'mindflow-f4a56.firebasestorage.app',
    androidClientId: '445806361703-2f6nhfu2slqtlb2lg2lupqhti5s9dhb1.apps.googleusercontent.com',
    iosClientId: '445806361703-c63hs22k23r667vlkmt8q7cvhfnpfolm.apps.googleusercontent.com',
    iosBundleId: 'com.khushalkhan.mindflow',
  );
}
